export const foodWordpack = {
  name: 'Food',
  id: 1,
  icon: 'food',
  words: [
    { id: 1, word: 'nutrition' },
    { id: 2, word: 'meal' },
    { id: 3, word: 'seafood' },
    { id: 4, word: 'vegetarian' },
    { id: 5, word: 'fruit' },
    { id: 6, word: 'vegetable' },
    { id: 7, word: 'seed' },
    { id: 8, word: 'products' },
    { id: 9, word: 'meat' },
    { id: 10, word: 'hunger' },
    { id: 11, word: 'protein' },
    { id: 12, word: 'solid_food' },
    { id: 13, word: 'junk_food' },
    { id: 14, word: 'breakfast' },
    { id: 15, word: 'lunch' },
    { id: 16, word: 'dinner' },
  ],
};

export const natureWordpack = {
  name: 'Nature',
  id: 2,
  icon: 'nature',
  words: [
    { id: 1, word: 'forest' },
    { id: 2, word: 'mountain' },
    { id: 3, word: 'river' },
    { id: 4, word: 'lake' },
    { id: 5, word: 'ocean' },
    { id: 6, word: 'island' },
    { id: 7, word: 'beach' },
    { id: 8, word: 'volcano' },
    { id: 9, word: 'jungle' },
    { id: 10, word: 'desert' },
    { id: 11, word: 'valley' },
    { id: 12, word: 'waterfall' },
    { id: 13, word: 'meadow' },
    { id: 14, word: 'stream' },
    { id: 15, word: 'prairie' },
    { id: 16, word: 'glacier' },
    { id: 17, word: 'canyon' },
    { id: 18, word: 'swamp' },
    { id: 19, word: 'rainforest' },
    { id: 20, word: 'savannah' },
  ],
};

export const seasonsWordpack = {
  name: 'Seasons',
  id: 3,
  icon: 'seasons',
  words: [
    { id: 1, word: 'spring' },
    { id: 2, word: 'summer' },
    { id: 3, word: 'fall' },
    { id: 4, word: 'autumn' },
    { id: 5, word: 'winter' },
    { id: 6, word: 'monsoon' },
    { id: 7, word: 'rainy' },
    { id: 8, word: 'dry' },
    { id: 9, word: 'warm' },
    { id: 10, word: 'cold' },
    { id: 11, word: 'chilly' },
    { id: 12, word: 'mild' },
    { id: 13, word: 'pleasant' },
    { id: 14, word: 'humid' },
    { id: 15, word: 'frosty' },
    { id: 16, word: 'snowy' },
    { id: 17, word: 'icy' },
    { id: 18, word: 'blizzard' },
  ],
};

export const cosmosWordpack = {
  name: 'Cosmsos',
  id: 4,
  icon: 'comsos',
  words: [
    { id: 1, word: 'planet' },
    { id: 2, word: 'star' },
    { id: 3, word: 'sun' },
    { id: 4, word: 'moon' },
    { id: 5, word: 'galaxy' },
    { id: 6, word: 'nebula' },
    { id: 7, word: 'astronomy' },
    { id: 8, word: 'cosmic' },
    { id: 9, word: 'universe' },
    { id: 10, word: 'comet' },
    { id: 11, word: 'meteor' },
    { id: 12, word: 'asteroid' },
    { id: 13, word: 'satellite' },
    { id: 14, word: 'spaceship' },
  ],
};

export const technologyWordpack = {
  name: 'Technology',
  id: 5,
  icon: 'technology',
  words: [
    { id: 1, word: 'computer' },
    { id: 2, word: 'smartphone' },
    { id: 3, word: 'internet' },
    { id: 4, word: 'laptop' },
    { id: 5, word: 'tablet' },
    { id: 6, word: 'robot' },
    { id: 7, word: 'drone' },
    { id: 8, word: 'software' },
    { id: 9, word: 'hardware' },
    { id: 10, word: 'programming' },
    { id: 11, word: 'code' },
    { id: 12, word: 'AI' },
    { id: 13, word: 'machine learning' },
    { id: 14, word: 'data science' },
    { id: 15, word: 'cybersecurity' },
  ],
};

export const animalsWordpack = {
  name: 'Animals',
  id: 6,
  icon: 'animals',
  words: [
    { id: 1, word: 'dog' },
    { id: 2, word: 'cat' },
    { id: 3, word: 'lion' },
    { id: 4, word: 'tiger' },
    { id: 5, word: 'elephant' },
    { id: 6, word: 'giraffe' },
    { id: 7, word: 'monkey' },
    { id: 8, word: 'zebra' },
    { id: 9, word: 'rhinoceros' },
    { id: 10, word: 'kangaroo' },
    { id: 11, word: 'panda' },
    { id: 12, word: 'horse' },
    { id: 13, word: 'deer' },
    { id: 14, word: 'bird' },
    { id: 15, word: 'fish' },
  ],
};

export const sportsWordpack = {
  name: 'Sports',
  id: 7,
  icon: 'sports',
  words: [
    { id: 1, word: 'football' },
    { id: 2, word: 'basketball' },
    { id: 3, word: 'tennis' },
    { id: 4, word: 'baseball' },
    { id: 5, word: 'golf' },
    { id: 6, word: 'boxing' },
    { id: 7, word: 'swimming' },
    { id: 8, word: 'gymnastics' },
    { id: 9, word: 'volleyball' },
    { id: 10, word: 'track and field' },
    { id: 11, word: 'hockey' },
    { id: 12, word: 'soccer' },
    { id: 13, word: 'wrestling' },
    { id: 14, word: 'judo' },
    { id: 15, word: 'karate' },
  ],
};

export const transportationWordpack = {
  name: 'Transportation',
  id: 8,
  icon: 'transportation',
  words: [
    { id: 1, word: 'car' },
    { id: 2, word: 'bus' },
    { id: 3, word: 'train' },
    { id: 4, word: 'airplane' },
    { id: 5, word: 'bicycle' },
    { id: 6, word: 'motorcycle' },
    { id: 7, word: 'taxi' },
    { id: 8, word: 'truck' },
    { id: 9, word: 'ship' },
    { id: 10, word: 'subway' },
    { id: 11, word: 'ferry' },
    { id: 12, word: 'helicopter' },
    { id: 13, word: 'hot air balloon' },
    { id: 14, word: 'rocket' },
    { id: 15, word: 'space shuttle' },
  ],
};
